# Generated by Django 5.2.6 on 2025-12-02 19:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_riesgos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAccidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('reportado', 'Reporte Flash (Pendiente de Investigación)'), ('en_investigacion', 'En Proceso de Investigación'), ('plan_accion', 'Plan de Acción / Medidas'), ('cerrado', 'Caso Cerrado')], db_index=True, default='reportado', max_length=20)),
                ('area_departamento', models.CharField(max_length=255, verbose_name='Área / Sección')),
                ('lugar_exacto', models.CharField(help_text='Ej: Pasillo 4, Bodega de Insumos', max_length=255)),
                ('supervisor_directo', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_completo_accidentado', models.CharField(blank=True, max_length=255, null=True)),
                ('rut_accidentado', models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT')),
                ('cargo_accidentado', models.CharField(blank=True, max_length=255, null=True)),
                ('antiguedad_cargo', models.CharField(blank=True, help_text='Tiempo en el cargo', max_length=100, null=True)),
                ('turno_accidentado', models.CharField(blank=True, choices=[('A', 'Turno A'), ('B', 'Turno B'), ('C', 'Turno C'), ('administrativo', 'Administrativo'), ('otro', 'Otro')], max_length=20, null=True)),
                ('horas_trabajadas_antes', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Horas trabajadas previo al evento')),
                ('fecha_accidente', models.DateTimeField(verbose_name='Fecha y Hora del Accidente')),
                ('descripcion_evento', models.TextField(help_text='Describa QUÉ pasó, CÓMO, DÓNDE y CUÁNDO. Sea objetivo.', verbose_name='Relato del Hecho')),
                ('tipo_accidente', models.CharField(choices=[('accidente_trabajo', 'Accidente del Trabajo (CTP/STP)'), ('accidente_trayecto', 'Accidente de Trayecto'), ('enfermedad_profesional', 'Enfermedad Profesional'), ('incidente', 'Incidente / Cuasi-Accidente (Sin Lesión)'), ('otro', 'Otro')], max_length=50)),
                ('severidad_inicial', models.CharField(choices=[('insignificante', '1. Insignificante (Cuasi Accidente)'), ('leve', '2. Leve (Primeros Auxilios / STP)'), ('seria', '3. Seria (Incapacidad Temporal / CTP)'), ('grave', '4. Grave (Invalidez Parcial / Daño Mayor)'), ('fatal', '5. Fatal o Catastrófica')], max_length=20)),
                ('parte_cuerpo_afectada', models.CharField(blank=True, help_text='Zona general detectada por el modelo 3D (ej: Mano Derecha)', max_length=255, null=True)),
                ('detalle_parte_afectada', models.CharField(blank=True, help_text='Especifique el detalle (ej: Dedo índice, falange distal)', max_length=255, null=True, verbose_name='Detalle Específico')),
                ('tipo_lesion', models.CharField(blank=True, choices=[('contusion', 'Contusión / Golpe'), ('corte', 'Corte / Laceración'), ('esguince', 'Esguince / Torcedura'), ('quemadura', 'Quemadura'), ('fractura', 'Fractura'), ('amputacion', 'Amputación'), ('lumbago', 'Lumbago'), ('otro', 'Otro')], max_length=50, null=True)),
                ('tratamiento_inicial', models.CharField(blank=True, choices=[('primeros_auxilios', 'Primeros Auxilios (Faena)'), ('policlinico', 'Atención en Policlínico'), ('mutual', 'Derivación a Organismo Administrador (Mutual/ACHS/IST/ISL)'), ('hospital', 'Traslado Urgencia (Hospital/Clínica)'), ('ninguno', 'Sin tratamiento')], max_length=50, null=True)),
                ('danio_propiedad', models.BooleanField(default=False, verbose_name='¿Daño a propiedad/equipos?')),
                ('detalle_danio_propiedad', models.TextField(blank=True, null=True)),
                ('danio_medio_ambiente', models.BooleanField(default=False, verbose_name='¿Daño al medio ambiente?')),
                ('medidas_inmediatas', models.TextField(help_text='¿Qué se hizo al instante? (Ej: Detención de faena, primeros auxilios, bloqueo).', verbose_name='Acciones Inmediatas')),
                ('evidencia_fotografica', models.ImageField(blank=True, null=True, upload_to='accidentes_evidencia/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_accidentes', to='gestion_riesgos.empresa')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestigacionAccidente',
            fields=[
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accidentes.reporteaccidente')),
                ('fecha_inicio_investigacion', models.DateField(default=django.utils.timezone.now)),
                ('equipo_investigador', models.TextField(help_text='Nombres y cargos del comité investigador')),
                ('factores_personales', models.TextField(blank=True, verbose_name='Factores Personales')),
                ('factores_trabajo', models.TextField(blank=True, verbose_name='Factores del Trabajo')),
                ('actos_subestandares', models.TextField(blank=True, verbose_name='Actos Subestándares')),
                ('condiciones_subestandares', models.TextField(blank=True, verbose_name='Condiciones Subestándares')),
                ('porque_1', models.TextField(blank=True, verbose_name='1. ¿Por qué ocurrió?')),
                ('porque_2', models.TextField(blank=True, verbose_name='2. ¿Por qué ocurrió lo anterior?')),
                ('porque_3', models.TextField(blank=True, verbose_name='3. ¿Por qué ocurrió lo anterior?')),
                ('porque_4', models.TextField(blank=True, verbose_name='4. ¿Por qué ocurrió lo anterior?')),
                ('porque_5', models.TextField(blank=True, verbose_name='5. ¿Por qué ocurrió lo anterior (Causa Raíz)?')),
                ('medida_eliminar', models.TextField(blank=True, verbose_name='Eliminar/Sustituir')),
                ('medida_ingenieria', models.TextField(blank=True, verbose_name='Control de Ingeniería')),
                ('medida_administrativa', models.TextField(blank=True, verbose_name='Administrativo')),
                ('medida_epp', models.TextField(blank=True, verbose_name='EPP')),
                ('responsable_implementacion', models.CharField(max_length=255)),
                ('fecha_plazo', models.DateField()),
                ('completada', models.BooleanField(default=False)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
