# Generated by Django 5.2.6 on 2025-10-09 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_riesgos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAccidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accidente', models.DateTimeField()),
                ('lugar_exacto', models.CharField(help_text='Ej: Taller de soldadura, Bodega 2', max_length=255)),
                ('tipo_accidente', models.CharField(choices=[('incidente', 'Incidente (Casi Accidente)'), ('leve', 'Leve (Sin Tiempo Perdido)'), ('grave', 'Grave (Con Tiempo Perdido)'), ('fatal', 'Fatal')], max_length=20)),
                ('descripcion_evento', models.TextField(help_text='Describe detalladamente qué sucedió.')),
                ('lesiones_sufridas', models.TextField(blank=True, help_text='Describe las lesiones de la persona, si aplica.')),
                ('nombres_involucrados', models.CharField(help_text='Nombres de los trabajadores involucrados.', max_length=255)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_accidentes', to='gestion_riesgos.empresa')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestigacionAccidente',
            fields=[
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accidentes.reporteaccidente')),
                ('causas_inmediatas', models.TextField(help_text='Condiciones y/o actos subestándares. Ej: Piso resbaladizo, no usar EPP.')),
                ('causas_basicas', models.TextField(help_text='Factores personales y/o de trabajo. Ej: Falta de capacitación, mantenimiento deficiente.')),
                ('medidas_correctivas', models.TextField(help_text='Detalla las medidas a implementar para evitar la recurrencia.')),
                ('responsables_implementacion', models.CharField(help_text='Nombres o cargos de los responsables.', max_length=255)),
                ('fecha_limite_implementacion', models.DateField()),
                ('completada', models.BooleanField(default=False)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('investigador_lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
