# Generated by Django 5.2.6 on 2026-07-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacionaccidente',
            name='antecedentes_recopilados',
            field=models.TextField(blank=True, help_text='Fotografías, procedimientos, permisos, capacitación, mantención, EPP y otros registros.', verbose_name='Antecedentes y evidencias recopiladas'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='aviso_dt_seremi',
            field=models.BooleanField(default=False, verbose_name='Aviso inmediato a DT y SEREMI de Salud'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='consideraciones_genero',
            field=models.TextField(blank=True, help_text='Considere diseño del trabajo, EPP, tareas, exposición, turnos y condiciones diferenciadas.', verbose_name='Enfoque de género y diversidad'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='diat_emitida',
            field=models.BooleanField(default=False, verbose_name='DIAT enviada al organismo administrador'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='faena_suspendida',
            field=models.BooleanField(default=False, verbose_name='Faena afectada suspendida y controlada'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='fecha_aviso_autoridad',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora del aviso'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='folio_diat',
            field=models.CharField(blank=True, max_length=100, verbose_name='Folio o comprobante DIAT'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='responsable_verificacion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Responsable de verificar eficacia'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='secuencia_evento',
            field=models.TextField(blank=True, help_text='Ordene hechos verificables antes, durante y después del evento; evite atribuir culpa.', verbose_name='Secuencia cronológica del evento'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='testigos_entrevistados',
            field=models.TextField(blank=True, verbose_name='Testigos entrevistados'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='trabajadores_participantes',
            field=models.TextField(blank=True, help_text='Personas trabajadoras, Comité Paritario, delegado/a o representantes que participaron.', verbose_name='Participación de trabajadores y representantes'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='verificacion_eficacia',
            field=models.TextField(blank=True, help_text='Indique cómo se comprobó que las medidas controlan la causa y no sólo que fueron ejecutadas.', verbose_name='Evidencia de eficacia'),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='criterio_gravedad_legal',
            field=models.CharField(choices=[('ninguno', 'No activa criterio legal grave/fatal'), ('por_confirmar', 'Por confirmar con organismo administrador'), ('fatal', 'Fatal: fallecimiento asociado al accidente'), ('reanimacion', 'Requirió maniobras de reanimación'), ('rescate', 'Requirió maniobras de rescate'), ('caida_altura', 'Caída desde una altura superior a 1,8 metros'), ('amputacion', 'Provocó amputación o pérdida inmediata de una parte del cuerpo'), ('multiple', 'Involucró a varias personas y alteró el desarrollo normal de la faena')], default='ninguno', help_text='Si existe más de un criterio, seleccione el de mayor impacto y detalle los demás en el relato.', max_length=30, verbose_name='Criterio legal de accidente grave o fatal'),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='sexo_accidentado',
            field=models.CharField(blank=True, choices=[('mujer', 'Mujer'), ('hombre', 'Hombre'), ('intersex', 'Intersex'), ('no_informa', 'Prefiere no informar')], help_text='Dato mínimo del registro de accidentes del D.S. N.º 44.', max_length=20, null=True, verbose_name='Sexo de la persona accidentada'),
        ),
    ]
