# Generated by Django 5.2.6 on 2025-10-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteaccidente',
            name='evidencia_fotografica',
            field=models.ImageField(blank=True, null=True, upload_to='accidentes_evidencia/', verbose_name='Evidencia Fotográfica'),
        ),
    ]
