# Generated by Django 5.2.6 on 2025-10-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0002_reporteaccidente_evidencia_fotografica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteaccidente',
            name='lesiones_sufridas',
        ),
        migrations.RemoveField(
            model_name='reporteaccidente',
            name='nombres_involucrados',
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='antiguedad_cargo_accidentado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='area_departamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='cargo_accidentado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='causas_inmediatas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='medidas_inmediatas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='nombre_completo_accidentado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='parte_cuerpo_afectada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='rut_accidentado',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='supervisor_responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='tipo_lesion',
            field=models.CharField(blank=True, choices=[('contusion', 'Contusión'), ('corte', 'Corte'), ('esguince', 'Esguince')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='tratamiento_inicial',
            field=models.CharField(blank=True, choices=[('primeros_auxilios', 'Primeros auxilios'), ('derivado_mutual', 'Derivado a mutual'), ('hospital', 'Hospital'), ('otro', 'Otro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='turno_accidentado',
            field=models.CharField(blank=True, choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='tipo_accidente',
            field=models.CharField(choices=[('incidente', 'Incidente (Casi Accidente)'), ('leve', 'Leve (Sin Tiempo Perdido)'), ('grave', 'Grave (Con Tiempo Perdido)'), ('fatal', 'Fatal'), ('dano_propiedad', 'Daño a la propiedad / equipo'), ('casi_accidente', 'Casi accidente')], max_length=20),
        ),
    ]
