# Generated by Django 5.2.6 on 2026-07-14 06:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0002_investigacionaccidente_antecedentes_recopilados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('relato_anonimizado', models.TextField(help_text='No incluya nombre, RUT, datos clínicos ni otros identificadores de la persona.')),
                ('aprendizaje_clave', models.TextField()),
                ('medidas_preventivas', models.TextField()),
                ('audiencia', models.CharField(default='Personas trabajadoras expuestas a tareas similares', max_length=255)),
                ('canales_difusion', models.CharField(blank=True, help_text='Ej: charla, correo, WhatsApp corporativo, cartelera.', max_length=255)),
                ('archivo_alerta', models.FileField(blank=True, null=True, upload_to='accidentes_alertas/')),
                ('revision_privacidad', models.BooleanField(default=False, verbose_name='Se revisó que la alerta no identifique a la persona')),
                ('difundida', models.BooleanField(default=False)),
                ('fecha_difusion', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerta_aprendizaje', to='accidentes.reporteaccidente')),
            ],
            options={
                'verbose_name': 'Alerta de aprendizaje',
                'verbose_name_plural': 'Alertas de aprendizaje',
            },
        ),
        migrations.CreateModel(
            name='DeclaracionAccidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_participacion', models.CharField(choices=[('accidentado', 'Persona accidentada'), ('testigo_directo', 'Testigo directo'), ('testigo_indirecto', 'Testigo indirecto'), ('supervisor', 'Supervisor/a o jefatura'), ('otro', 'Otra persona entrevistada')], max_length=30)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('rut', models.CharField(blank=True, max_length=12, verbose_name='RUT')),
                ('cargo', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('fecha_declaracion', models.DateField(default=django.utils.timezone.localdate)),
                ('actividad_al_momento', models.TextField(verbose_name='Qué estaba haciendo cuando ocurrió el evento')),
                ('como_ocurrio_lesion', models.TextField(blank=True, verbose_name='Cómo ocurrió la lesión o evento')),
                ('que_provoco_lesion', models.TextField(blank=True, verbose_name='Qué elemento o condición produjo la lesión')),
                ('notifico_mismo_dia', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('no_aplica', 'No aplica / no corresponde')], default='si', max_length=20)),
                ('aviso_a', models.CharField(blank=True, max_length=255, verbose_name='A quién dio aviso')),
                ('testigos_identificados', models.TextField(blank=True, verbose_name='Testigos identificados')),
                ('jefatura_directa', models.CharField(blank=True, max_length=255)),
                ('cargo_jefatura', models.CharField(blank=True, max_length=255)),
                ('relato', models.TextField(help_text='Registre hechos en primera persona. No complete causas ni conclusiones por la persona.', verbose_name='Relato libre de la persona entrevistada')),
                ('croquis_o_evidencia', models.FileField(blank=True, null=True, upload_to='accidentes_declaraciones/', verbose_name='Croquis, fotografía o declaración firmada')),
                ('firma_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre consignado como firma')),
                ('confirmada_por_declarante', models.BooleanField(default=False, verbose_name='La persona confirma que el relato representa su declaración')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaraciones', to='accidentes.reporteaccidente')),
            ],
            options={
                'verbose_name': 'Declaración de accidente',
                'verbose_name_plural': 'Declaraciones de accidente',
                'ordering': ['fecha_declaracion', 'creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoMutualAccidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('reca', 'RECA / resolución de calificación'), ('alta_medica', 'Alta médica'), ('certificado_atencion', 'Certificado de atención'), ('diat_comprobante', 'Comprobante DIAT'), ('licencia', 'Licencia u orden de reposo'), ('otro', 'Otro antecedente recibido')], max_length=30)),
                ('archivo', models.FileField(upload_to='accidentes_mutual/')),
                ('emitido_por', models.CharField(blank=True, max_length=255, verbose_name='Organismo o entidad emisora')),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_mutual', to='accidentes.reporteaccidente')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de mutualidad',
                'verbose_name_plural': 'Documentos de mutualidad',
                'ordering': ['tipo_documento', '-subido_en'],
            },
        ),
    ]
