# Generated by Django 5.2.6 on 2025-11-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0003_remove_reporteaccidente_lesiones_sufridas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteaccidente',
            name='clasificacion_severidad',
            field=models.CharField(blank=True, choices=[('incidente', 'Incidente (Casi Accidente)'), ('leve', 'Leve (Sin Tiempo Perdido)'), ('grave', 'Grave (Con Tiempo Perdido)'), ('fatal', 'Fatal')], help_text='Uso interno, no corresponde a la norma', max_length=16, null=True, verbose_name='Clasificación de Severidad (Interna)'),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='danio_propiedad',
            field=models.BooleanField(default=False, help_text='Dato adicional, no es un tipo de accidente', verbose_name='Daño a la propiedad/equipo'),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='detalle_danio_propiedad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='tipo_accidente',
            field=models.CharField(choices=[('accidente_trabajo', 'Accidente del Trabajo'), ('accidente_trayecto', 'Accidente de Trayecto'), ('enfermedad_profesional', 'Enfermedad Profesional'), ('accidente_sin_incapacidad', 'Accidente ocurrido a causa u ocasión del trabajo sin incapacidad'), ('enfermedad_laboral_sin_incapacidad', 'Enfermedad laboral sin incapacidad temporal ni permanente'), ('accidente_comun', 'Accidente común'), ('enfermedad_comun', 'Enfermedad común')], max_length=64),
        ),
    ]
