# Generated by Django 5.2.6 on 2025-12-01 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0004_reporteaccidente_clasificacion_severidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigacionaccidente',
            old_name='fecha_limite_implementacion',
            new_name='fecha_plazo',
        ),
        migrations.RenameField(
            model_name='reporteaccidente',
            old_name='antiguedad_cargo_accidentado',
            new_name='supervisor_directo',
        ),
        migrations.RemoveField(
            model_name='investigacionaccidente',
            name='causas_basicas',
        ),
        migrations.RemoveField(
            model_name='investigacionaccidente',
            name='causas_inmediatas',
        ),
        migrations.RemoveField(
            model_name='investigacionaccidente',
            name='investigador_lider',
        ),
        migrations.RemoveField(
            model_name='investigacionaccidente',
            name='medidas_correctivas',
        ),
        migrations.RemoveField(
            model_name='investigacionaccidente',
            name='responsables_implementacion',
        ),
        migrations.RemoveField(
            model_name='reporteaccidente',
            name='causas_inmediatas',
        ),
        migrations.RemoveField(
            model_name='reporteaccidente',
            name='clasificacion_severidad',
        ),
        migrations.RemoveField(
            model_name='reporteaccidente',
            name='supervisor_responsable',
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='actos_subestandares',
            field=models.TextField(blank=True, help_text='Acciones inseguras (No usar EPP, operar sin autorización).', verbose_name='Actos Subestándares'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='condiciones_subestandares',
            field=models.TextField(blank=True, help_text='Entorno peligroso (Piso resbaladizo, ruido, iluminación).', verbose_name='Condiciones Subestándares'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='equipo_investigador',
            field=models.TextField(default='sin asignar', help_text='Nombres y cargos del comité investigador (Comité Paritario, etc.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='factores_personales',
            field=models.TextField(blank=True, help_text='No sabe, no puede, no quiere (Fatiga, estrés, falta de capacitación).', verbose_name='Factores Personales'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='factores_trabajo',
            field=models.TextField(blank=True, help_text='Falta de supervisión, diseño inadecuado, mantenimiento deficiente.', verbose_name='Factores del Trabajo'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='fecha_inicio_investigacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='medida_administrativa',
            field=models.TextField(blank=True, help_text='Procedimientos, señalética, capacitación, turnos.', verbose_name='Administrativo'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='medida_eliminar',
            field=models.TextField(blank=True, help_text='Eliminar el peligro o sustituir por uno menor (Barrera Dura).', verbose_name='Eliminar/Sustituir'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='medida_epp',
            field=models.TextField(blank=True, help_text='Elementos de Protección Personal (Última barrera).', verbose_name='EPP'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='medida_ingenieria',
            field=models.TextField(blank=True, help_text='Aislamiento, protecciones, rediseño (Barrera Dura).', verbose_name='Control de Ingeniería'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='porque_1',
            field=models.TextField(blank=True, verbose_name='1. ¿Por qué ocurrió?'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='porque_2',
            field=models.TextField(blank=True, verbose_name='2. ¿Por qué ocurrió lo anterior?'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='porque_3',
            field=models.TextField(blank=True, verbose_name='3. ¿Por qué ocurrió lo anterior?'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='porque_4',
            field=models.TextField(blank=True, verbose_name='4. ¿Por qué ocurrió lo anterior?'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='porque_5',
            field=models.TextField(blank=True, verbose_name='5. ¿Por qué ocurrió lo anterior (Causa Raíz)?'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='responsable_implementacion',
            field=models.CharField(default='sin asignar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='antiguedad_cargo',
            field=models.CharField(blank=True, help_text='Tiempo en el cargo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='danio_medio_ambiente',
            field=models.BooleanField(default=False, verbose_name='¿Daño al medio ambiente?'),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='estado',
            field=models.CharField(choices=[('reportado', 'Reporte Flash (Pendiente de Investigación)'), ('en_investigacion', 'En Proceso de Investigación'), ('plan_accion', 'Plan de Acción / Medidas'), ('cerrado', 'Caso Cerrado')], db_index=True, default='reportado', max_length=20),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='horas_trabajadas_antes',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Horas trabajadas previo al evento'),
        ),
        migrations.AddField(
            model_name='reporteaccidente',
            name='severidad_inicial',
            field=models.CharField(choices=[('insignificante', '1. Insignificante (Cuasi Accidente)'), ('leve', '2. Leve (Primeros Auxilios / STP)'), ('seria', '3. Seria (Incapacidad Temporal / CTP)'), ('grave', '4. Grave (Invalidez Parcial / Daño Mayor)'), ('fatal', '5. Fatal o Catastrófica')], default='sin asignar', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='area_departamento',
            field=models.CharField(default='sin asignar', max_length=255, verbose_name='Área / Sección'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='danio_propiedad',
            field=models.BooleanField(default=False, verbose_name='¿Daño a propiedad/equipos?'),
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='descripcion_evento',
            field=models.TextField(help_text='Describa QUÉ pasó, CÓMO, DÓNDE y CUÁNDO. Sea objetivo.', verbose_name='Relato del Hecho'),
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='evidencia_fotografica',
            field=models.ImageField(blank=True, null=True, upload_to='accidentes_evidencia/'),
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='fecha_accidente',
            field=models.DateTimeField(verbose_name='Fecha y Hora del Accidente'),
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='lugar_exacto',
            field=models.CharField(help_text='Ej: Pasillo 4, Bodega de Insumos', max_length=255),
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='medidas_inmediatas',
            field=models.TextField(help_text='¿Qué se hizo al instante? (Ej: Detención de faena, primeros auxilios, bloqueo).', verbose_name='Acciones Inmediatas'),
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='parte_cuerpo_afectada',
            field=models.CharField(blank=True, help_text='Dato del modelo 3D', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='rut_accidentado',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='tipo_accidente',
            field=models.CharField(choices=[('accidente_trabajo', 'Accidente del Trabajo (CTP/STP)'), ('accidente_trayecto', 'Accidente de Trayecto'), ('enfermedad_profesional', 'Enfermedad Profesional'), ('incidente', 'Incidente / Cuasi-Accidente (Sin Lesión)'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='tipo_lesion',
            field=models.CharField(blank=True, choices=[('contusion', 'Contusión / Golpe'), ('corte', 'Corte / Laceración'), ('esguince', 'Esguince / Torcedura'), ('quemadura', 'Quemadura'), ('fractura', 'Fractura'), ('amputacion', 'Amputación'), ('lumbago', 'Lumbago'), ('otro', 'Otro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='tratamiento_inicial',
            field=models.CharField(blank=True, choices=[('primeros_auxilios', 'Primeros Auxilios (Faena)'), ('policlinico', 'Atención en Policlínico'), ('mutual', 'Derivación a Organismo Administrador (Mutual/ACHS/IST/ISL)'), ('hospital', 'Traslado Urgencia (Hospital/Clínica)'), ('ninguno', 'Sin tratamiento')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='turno_accidentado',
            field=models.CharField(blank=True, choices=[('A', 'Turno A'), ('B', 'Turno B'), ('C', 'Turno C'), ('administrativo', 'Administrativo'), ('otro', 'Otro')], max_length=20, null=True),
        ),
    ]
