# Generated by Django 5.2.6 on 2025-12-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0005_rename_fecha_limite_implementacion_investigacionaccidente_fecha_plazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteaccidente',
            name='detalle_parte_afectada',
            field=models.CharField(blank=True, help_text='Especifique el detalle (ej: Dedo índice, falange distal)', max_length=255, null=True, verbose_name='Detalle Específico'),
        ),
        migrations.AlterField(
            model_name='investigacionaccidente',
            name='actos_subestandares',
            field=models.TextField(blank=True, verbose_name='Actos Subestándares'),
        ),
        migrations.AlterField(
            model_name='investigacionaccidente',
            name='condiciones_subestandares',
            field=models.TextField(blank=True, verbose_name='Condiciones Subestándares'),
        ),
        migrations.AlterField(
            model_name='investigacionaccidente',
            name='equipo_investigador',
            field=models.TextField(help_text='Nombres y cargos del comité investigador'),
        ),
        migrations.AlterField(
            model_name='investigacionaccidente',
            name='factores_personales',
            field=models.TextField(blank=True, verbose_name='Factores Personales'),
        ),
        migrations.AlterField(
            model_name='investigacionaccidente',
            name='factores_trabajo',
            field=models.TextField(blank=True, verbose_name='Factores del Trabajo'),
        ),
        migrations.AlterField(
            model_name='investigacionaccidente',
            name='medida_administrativa',
            field=models.TextField(blank=True, verbose_name='Administrativo'),
        ),
        migrations.AlterField(
            model_name='investigacionaccidente',
            name='medida_eliminar',
            field=models.TextField(blank=True, verbose_name='Eliminar/Sustituir'),
        ),
        migrations.AlterField(
            model_name='investigacionaccidente',
            name='medida_epp',
            field=models.TextField(blank=True, verbose_name='EPP'),
        ),
        migrations.AlterField(
            model_name='investigacionaccidente',
            name='medida_ingenieria',
            field=models.TextField(blank=True, verbose_name='Control de Ingeniería'),
        ),
        migrations.AlterField(
            model_name='reporteaccidente',
            name='parte_cuerpo_afectada',
            field=models.CharField(blank=True, help_text='Zona general detectada por el modelo 3D (ej: Mano Derecha)', max_length=255, null=True),
        ),
    ]
