# Generated by Django 5.2.6 on 2025-12-02 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_riesgos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prevencionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto de la Visita')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado Actual')),
                ('email_solicitud', models.EmailField(blank=True, help_text='Correo al que se enviará la notificación de solicitud.', max_length=254, null=True, verbose_name='Correo de Contacto')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_riesgos.empresa', verbose_name='Empresa Cliente')),
            ],
            options={
                'verbose_name': 'Visita Técnica',
                'verbose_name_plural': 'Visitas Técnicas',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
