# Generated by Django 5.2.6 on 2026-07-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, verbose_name='Duración estimada (minutos)'),
        ),
        migrations.AddField(
            model_name='visita',
            name='fecha_proxima_accion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de próxima acción'),
        ),
        migrations.AddField(
            model_name='visita',
            name='objetivo',
            field=models.TextField(blank=True, help_text='Defina qué decisión, evidencia o acuerdo debe obtenerse.', verbose_name='Objetivo y resultado esperado'),
        ),
        migrations.AddField(
            model_name='visita',
            name='proxima_accion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Próxima acción acordada'),
        ),
        migrations.AddField(
            model_name='visita',
            name='resultado',
            field=models.TextField(blank=True, verbose_name='Resultado o acuerdos'),
        ),
        migrations.AddField(
            model_name='visita',
            name='tipo_gestion',
            field=models.CharField(choices=[('VISITA', 'Visita en terreno'), ('VIDEOLLAMADA', 'Videollamada'), ('LLAMADA', 'Llamada telefónica'), ('EMAIL', 'Correo de seguimiento')], default='VISITA', max_length=20, verbose_name='Canal de gestión'),
        ),
    ]
