# Generated by Django 5.2.6 on 2025-10-09 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_riesgos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_obligacion', models.CharField(help_text='Ej: Declaración de Emisiones Atmosféricas', max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(help_text='Primera fecha en que la obligación debe cumplirse.')),
                ('frecuencia', models.CharField(choices=[('puntual', 'Puntual'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='puntual', max_length=20)),
                ('proxima_fecha_vencimiento', models.DateField()),
                ('responsable', models.CharField(blank=True, help_text='Nombre o email del responsable.', max_length=255)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateField(blank=True, null=True)),
                ('notificacion_email', models.EmailField(blank=True, help_text='Email para recibir notificaciones de esta tarea.', max_length=254)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_legales', to='gestion_riesgos.empresa')),
                ('normativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_riesgos.normativa')),
            ],
        ),
    ]
