# Generated by Django 5.2.6 on 2026-07-14 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumplimiento', '0001_initial'),
        ('gestion_riesgos', '0003_remove_detalleiper_eval_clasificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(choices=[('prexor', 'PREXOR · Exposición ocupacional a ruido'), ('tmert', 'TMERT · Trastornos musculoesqueléticos'), ('silice', 'Sílice · Vigilancia ambiental y de salud'), ('psicosocial', 'Riesgos psicosociales · CEAL-SM/SUSESO'), ('uv_solar', 'Radiación UV solar'), ('mmc', 'Manejo o manipulación manual de carga'), ('hipobaria', 'Hipobaria intermitente crónica por gran altitud')], max_length=30)),
                ('estado', models.CharField(choices=[('POR_EVALUAR', 'Por evaluar'), ('NO_APLICA', 'No aplica con justificación'), ('APLICA', 'Aplica · diagnóstico pendiente'), ('IMPLEMENTACION', 'Medidas en implementación'), ('VIGILANCIA', 'En vigilancia'), ('CONTROLADO', 'Controlado · mantener seguimiento')], default='POR_EVALUAR', max_length=20)),
                ('agente_identificado', models.BooleanField(default=False, verbose_name='Peligro o agente identificado')),
                ('diagnostico_exposicion', models.TextField(blank=True, help_text='Describa tareas, puestos, fuente, duración y evidencia usada para decidir aplicabilidad.', verbose_name='Diagnóstico de exposición o justificación')),
                ('personas_expuestas', models.PositiveIntegerField(default=0, verbose_name='Personas potencialmente expuestas')),
                ('responsable', models.CharField(blank=True, max_length=255)),
                ('organismo_administrador', models.CharField(blank=True, max_length=255, verbose_name='Organismo administrador Ley N.º 16.744')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha de evaluación')),
                ('proxima_revision', models.DateField(blank=True, null=True, verbose_name='Próxima revisión')),
                ('medidas_control', models.TextField(blank=True, verbose_name='Medidas y acciones comprometidas')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='protocolos_minsal/')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_protocolos', to='gestion_riesgos.empresa')),
            ],
            options={
                'verbose_name': 'Evaluación de protocolo MINSAL',
                'verbose_name_plural': 'Evaluaciones de protocolos MINSAL',
                'ordering': ['empresa__razon_social', 'protocolo'],
                'unique_together': {('empresa', 'protocolo')},
            },
        ),
    ]
