# Generated by Django 5.2.6 on 2025-10-02 21:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: D.S. N° 594', max_length=255)),
                ('descripcion', models.TextField(help_text='Reglamento sobre condiciones sanitarias y ambientales básicas...')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='legislacion/')),
                ('fuente', models.URLField(blank=True, help_text='Enlace a fuente oficial.')),
                ('categoria', models.CharField(blank=True, help_text='Ej: Seguridad, Salud Ocupacional', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Peligro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia_riesgo', models.CharField(help_text='Ej: Riesgos de Seguridad', max_length=255)),
                ('riesgo_especifico', models.CharField(help_text='Ej: Caída de personas', max_length=255)),
                ('definicion', models.TextField(blank=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('rut', models.CharField(help_text='Ej: 76.123.456-7', max_length=12, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('prevencionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_gestionadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos_empresa/')),
                ('categoria', models.CharField(blank=True, help_text='Ej: Procedimientos, Charlas, Informes', max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion_riesgos.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='gestion_riesgos.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(help_text='Nombre del proyecto o área evaluada', max_length=255)),
                ('estado', models.CharField(default='En Elaboración', max_length=50)),
                ('version', models.PositiveIntegerField(default=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrices', to='gestion_riesgos.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Proceso de Soldadura', max_length=255)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='gestion_riesgos.matriz')),
            ],
            options={
                'unique_together': {('matriz', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecuencias', models.TextField(blank=True, help_text='Ej: Golpes, fracturas')),
                ('probabilidad_seguridad', models.PositiveIntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (4, 'Alta')], null=True, verbose_name='Probabilidad S&E')),
                ('consecuencia_seguridad', models.PositiveIntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (4, 'Alta')], null=True, verbose_name='Consecuencia S&E')),
                ('probabilidad_higienicos', models.PositiveIntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (4, 'Alta')], null=True, verbose_name='Probabilidad Higiene')),
                ('consecuencia_higienicos', models.PositiveIntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (4, 'Alta')], null=True, verbose_name='Consecuencia Higiene')),
                ('probabilidad_psicosociales', models.PositiveIntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (4, 'Alta')], null=True, verbose_name='Probabilidad Psicosocial')),
                ('consecuencia_psicosociales', models.PositiveIntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (4, 'Alta')], null=True, verbose_name='Consecuencia Psicosocial')),
                ('probabilidad_musculoesqueleticos', models.PositiveIntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (4, 'Alta')], null=True, verbose_name='Probabilidad M-E')),
                ('consecuencia_musculoesqueleticos', models.PositiveIntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (4, 'Alta')], null=True, verbose_name='Consecuencia M-E')),
                ('probabilidad_residual', models.PositiveIntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (4, 'Alta')], null=True)),
                ('consecuencia_residual', models.PositiveIntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (4, 'Alta')], null=True)),
                ('peligro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riesgos_asociados', to='gestion_riesgos.peligro')),
            ],
        ),
        migrations.CreateModel(
            name='MedidaControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas_control', to='gestion_riesgos.riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Firma'), ('firmado', 'Firmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('token_acceso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_firma', to='gestion_riesgos.documento')),
                ('firmante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_riesgos.contacto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto_trabajo', models.CharField(help_text='Ej: Soldador Calificado', max_length=255)),
                ('descripcion', models.CharField(help_text='Ej: Cortar planchas de metal', max_length=255)),
                ('es_rutinaria', models.BooleanField(default=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='gestion_riesgos.proceso')),
            ],
        ),
        migrations.AddField(
            model_name='riesgo',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='gestion_riesgos.tarea'),
        ),
    ]
