# Generated by Django 5.2.6 on 2025-09-11 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Proceso de Soldadura', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subproceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto_trabajo', models.CharField(help_text='Ej: Soldador Calificado', max_length=255)),
                ('tarea', models.CharField(help_text='Ej: Cortar planchas de metal', max_length=255)),
                ('es_rutinaria', models.BooleanField(default=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocesos', to='gestion_riesgos.proceso')),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo_especifico', models.CharField(help_text='Ej: Caída de objetos', max_length=255)),
                ('consecuencias', models.TextField(blank=True, help_text='Ej: Golpes, fracturas')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('probabilidad', models.IntegerField(choices=[(1, 'Baja (1)'), (2, 'Media (2)'), (4, 'Alta (4)')], default=1)),
                ('consecuencia_valor', models.IntegerField(choices=[(1, 'Ligeramente Dañino (1)'), (2, 'Dañino (2)'), (4, 'Extremadamente Dañino (4)')], default=1)),
                ('clasificacion_riesgo', models.CharField(blank=True, editable=False, max_length=50)),
                ('subproceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='gestion_riesgos.subproceso')),
            ],
        ),
    ]
