# Generated by Django 5.2.6 on 2025-09-11 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Proceso de Soldadura', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo_especifico', models.CharField(help_text='Ej: Caída de objetos', max_length=255)),
                ('consecuencias', models.TextField(blank=True, help_text='Ej: Golpes, fracturas')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('probabilidad', models.IntegerField(choices=[(1, 'Baja (1)'), (2, 'Media (2)'), (4, 'Alta (4)')], default=1, verbose_name='Probabilidad Inherente')),
                ('consecuencia_valor', models.IntegerField(choices=[(1, 'Ligeramente Dañino (1)'), (2, 'Dañino (2)'), (4, 'Extremadamente Dañino (4)')], default=1, verbose_name='Consecuencia Inherente')),
                ('clasificacion_riesgo', models.CharField(blank=True, editable=False, max_length=50)),
                ('probabilidad_residual', models.IntegerField(blank=True, choices=[(1, 'Baja (1)'), (2, 'Media (2)'), (4, 'Alta (4)')], null=True, verbose_name='Probabilidad Residual')),
                ('consecuencia_residual', models.IntegerField(blank=True, choices=[(1, 'Ligeramente Dañino (1)'), (2, 'Dañino (2)'), (4, 'Extremadamente Dañino (4)')], null=True, verbose_name='Consecuencia Residual')),
                ('clasificacion_riesgo_residual', models.CharField(blank=True, editable=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedidaControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Describe la medida de control implementada.')),
                ('tipo_control', models.CharField(choices=[('EL', 'Eliminación'), ('SU', 'Sustitución'), ('CI', 'Control de Ingeniería'), ('CA', 'Control Administrativo'), ('EP', 'Equipo de Protección Personal')], max_length=2)),
                ('responsable', models.CharField(help_text='Cargo o nombre del responsable', max_length=100)),
                ('plazo_implementacion', models.DateField()),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas_control', to='gestion_riesgos.riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='Subproceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto_trabajo', models.CharField(help_text='Ej: Soldador Calificado', max_length=255)),
                ('tarea', models.CharField(help_text='Ej: Cortar planchas de metal', max_length=255)),
                ('es_rutinaria', models.BooleanField(default=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocesos', to='gestion_riesgos.proceso')),
            ],
        ),
        migrations.AddField(
            model_name='riesgo',
            name='subproceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='gestion_riesgos.subproceso'),
        ),
    ]
