# Generated by Django 5.2.6 on 2025-12-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riesgos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleiper',
            name='cantidad_hombres',
            field=models.PositiveIntegerField(default=0, verbose_name='Cant. Hombres'),
        ),
        migrations.AddField(
            model_name='detalleiper',
            name='cantidad_mujeres',
            field=models.PositiveIntegerField(default=0, verbose_name='Cant. Mujeres'),
        ),
        migrations.AlterField(
            model_name='detalleiper',
            name='genero',
            field=models.CharField(blank=True, help_text='Hombre - Mujer - Ambos', max_length=50, null=True, verbose_name='Género'),
        ),
    ]
