# Generated by Django 5.2.6 on 2025-10-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riesgos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='subproceso',
            field=models.CharField(blank=True, help_text='Subproceso (Opcional)', max_length=255, verbose_name='Subproceso'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='adolescentes_h',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Adolescentes H'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='adolescentes_m',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Adolescentes M'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='adultos_mayores_h',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Adultos Mayores H'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='adultos_mayores_m',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Adultos Mayores M'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='consecuencia_especial',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (4, 'Alta')], null=True, verbose_name='Consecuencia Especial'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='discapacidad_cognitiva_h',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Disc. Cognitiva Hombres'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='discapacidad_cognitiva_m',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Disc. Cognitiva Mujeres'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='discapacidad_fisica_h',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Disc. Física Hombres'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='discapacidad_fisica_m',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Disc. Física Mujeres'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='discapacidad_sensorial_h',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Disc. Sensorial Hombres'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='discapacidad_sensorial_m',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Disc. Sensorial Mujeres'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='fecha_ejecucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Ejecución'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='fecha_seguimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Seguimiento'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='identificacion_gema',
            field=models.CharField(choices=[('G', 'Gente'), ('E', 'Equipo'), ('M', 'Material'), ('A', 'Ambiente'), ('N/A', 'No Aplica')], default='N/A', max_length=10, verbose_name='GEMA'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='medidas_control_especiales',
            field=models.TextField(blank=True, help_text='Medidas para grupos con discapacidades o condiciones especiales', verbose_name='Medidas Control Especiales'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='nueva_medida_control',
            field=models.TextField(blank=True, help_text='Nueva medida de control o eliminación (Opcional)', verbose_name='Nueva Medida de Control'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='probabilidad_especial',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (4, 'Alta')], null=True, verbose_name='Probabilidad Especial'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='requisito_legal',
            field=models.CharField(blank=True, help_text='Requisito legal asociado a la medida de control', max_length=255, verbose_name='Requisito Legal'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='responsable_gestion',
            field=models.CharField(blank=True, help_text='Persona o departamento responsable de gestionar', max_length=255, verbose_name='Responsable Gestión'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='responsable_seguimiento',
            field=models.CharField(blank=True, help_text='Responsable del seguimiento MIPER', max_length=255, verbose_name='Responsable Seguimiento'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='trabajadora_embarazada',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Trab. Embarazada'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='trabajadora_lactancia',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Trab. Lactancia'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='genero_hombres',
            field=models.PositiveIntegerField(default=0, help_text='Número de hombres involucrados', verbose_name='N° Hombres'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='genero_mujeres',
            field=models.PositiveIntegerField(default=0, help_text='Número de mujeres involucradas', verbose_name='N° Mujeres'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='herramientas_equipos',
            field=models.TextField(blank=True, help_text='Equipos y herramientas utilizados', verbose_name='Herramientas y Equipos'),
        ),
    ]
