# Generated by Django 5.2.6 on 2025-12-02 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riesgos', '0002_proceso_subproceso_riesgo_adolescentes_h_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizIPER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('departamento_sucursal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Departamento o Sucursal')),
                ('proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Revisión/Versión')),
                ('fecha_documento', models.DateField(blank=True, null=True, verbose_name='Fecha del Documento')),
                ('elaborado_por', models.CharField(blank=True, max_length=255, null=True, verbose_name='Elaborado por')),
                ('cargo_elabora', models.CharField(blank=True, default='Encargado Prevención de Riesgos', max_length=255, null=True)),
                ('revisado_por', models.CharField(blank=True, max_length=255, null=True, verbose_name='Revisado por')),
                ('cargo_revisa', models.CharField(blank=True, default='Gerente de Servicios', max_length=255, null=True)),
                ('aprobado_por', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aprobado por')),
                ('cargo_aprueba', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_cliente', models.ImageField(blank=True, null=True, upload_to='logos_matrices/', verbose_name='Logo Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_riesgos.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIPER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proceso')),
                ('genero', models.CharField(blank=True, help_text='Hombre - Mujer - Ambos - Otro', max_length=50, null=True, verbose_name='Género')),
                ('puesto_trabajo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Puesto de Trabajo')),
                ('tarea', models.TextField(blank=True, null=True, verbose_name='Tarea')),
                ('tipo_rutina', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rutinaria/No Rutinaria')),
                ('codigo_riesgo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cod. Riesgo')),
                ('peligro_factor', models.TextField(blank=True, null=True, verbose_name='Peligro / Factor')),
                ('riesgo', models.TextField(blank=True, null=True, verbose_name='Riesgo')),
                ('consecuencia', models.TextField(blank=True, null=True, verbose_name='Consecuencias')),
                ('gema', models.CharField(blank=True, help_text='Gente, Equipo, Material, Ambiente', max_length=100, null=True, verbose_name='GEMA')),
                ('medida_control_actual', models.TextField(blank=True, null=True, verbose_name='Medida Control Actual')),
                ('eval_probabilidad', models.IntegerField(blank=True, default=0, null=True, verbose_name='P')),
                ('eval_severidad', models.IntegerField(blank=True, default=0, null=True, verbose_name='S')),
                ('eval_valor', models.IntegerField(blank=True, default=0, null=True, verbose_name='Valor Riesgo')),
                ('eval_clasificacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clasificación')),
                ('requisito_legal', models.TextField(blank=True, null=True, verbose_name='Requisito Legal')),
                ('responsable_ejecucion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resp. Ejecución')),
                ('responsable_seguimiento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resp. Seguimiento')),
                ('residual_probabilidad', models.IntegerField(blank=True, default=0, null=True, verbose_name='P (Res)')),
                ('residual_severidad', models.IntegerField(blank=True, default=0, null=True, verbose_name='S (Res)')),
                ('residual_valor', models.IntegerField(blank=True, default=0, null=True, verbose_name='Valor (Res)')),
                ('residual_clasificacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clasificación (Res)')),
                ('condicion_especial', models.TextField(blank=True, help_text='Si no cuenta con trabajadores...', null=True, verbose_name='Condición Especial')),
                ('reevaluacion', models.TextField(blank=True, null=True, verbose_name='Reevaluación Especial')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='gestion_riesgos.matriziper')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
