# Generated by Django 5.2.6 on 2026-07-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riesgos', '0003_remove_detalleiper_eval_clasificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleiper',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='matriziper',
            name='mapa_actualizado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización del mapa'),
        ),
        migrations.AddField(
            model_name='matriziper',
            name='mapa_participacion',
            field=models.TextField(blank=True, help_text='Comité Paritario, delegado/a, trabajadores y asistencia técnica que participaron.', verbose_name='Participación en la elaboración'),
        ),
        migrations.AddField(
            model_name='matriziper',
            name='mapa_publicado',
            field=models.BooleanField(default=False, verbose_name='Mapa vigente y visible en el lugar de trabajo'),
        ),
        migrations.AddField(
            model_name='matriziper',
            name='mapa_riesgos_archivo',
            field=models.FileField(blank=True, null=True, upload_to='mapas_riesgo/', verbose_name='Mapa de riesgos publicado'),
        ),
        migrations.AddField(
            model_name='matriziper',
            name='mapa_ubicaciones',
            field=models.TextField(blank=True, help_text='Registre los sitios físicos y, si aplica, el enlace o QR de difusión.', verbose_name='Ubicaciones visibles donde se instaló'),
        ),
        migrations.AddField(
            model_name='matriziper',
            name='mapa_version',
            field=models.CharField(blank=True, max_length=30, verbose_name='Versión del mapa'),
        ),
        migrations.AlterField(
            model_name='detalleiper',
            name='residual_probabilidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='P (Res)'),
        ),
        migrations.AlterField(
            model_name='detalleiper',
            name='residual_severidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='S (Res)'),
        ),
        migrations.AlterField(
            model_name='detalleiper',
            name='residual_valor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor (Res)'),
        ),
    ]
